name: Build and test

on:
  push:
  pull_request_target:
    types: [labeled]

env:
  NODE_VERSION: 16
  JAVA_VERSION: 17

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')" # can the if also be est for all jobs?
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install npm dependencies
        working-directory: frontend
        run: npm install
      - name: Build and Test frontend
        working-directory: frontend
        run: npm test
      - name: Deploy frontend
        working-directory: frontend
        run: npm run dist
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build and Test backend
        working-directory: backend
        run: mvn -B clean install