name: CI Build

on:
  push:
  pull_request_target:
    types: [labeled]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: false

env:
  NODE_VERSION: 16
  JAVA_VERSION: 17

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')" # can the if also be est for all jobs?
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install npm dependencies
        working-directory: frontend
        run: npm install
      - name: Build and test frontend
        working-directory: frontend
        run: npm test
      - name: Deploy frontend
        working-directory: frontend
        run: npm run dist
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build and test backend
        working-directory: backend
        run: mvn -B clean verify
      - id: get_tag
        if: github.event.inputs.tag != '' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop'
        run: |
          if [[ ! -z "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF/refs\/tags\//}
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            TAG="develop"
          else
            TAG="snapshot"
          fi
          echo ::set-output name=tag::${TAG}
      - name: Build and push container image
        if: github.event.inputs.tag != '' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop'
        working-directory: backend
        run: mvn -B clean package -DskipTests
        env:
          QUARKUS_JIB_PLATFORMS: linux/amd64,linux/arm64/v8
          QUARKUS_CONTAINER_IMAGE_TAG: ${{ steps.get_tag.outputs.tag }}
          QUARKUS_CONTAINER_IMAGE_BUILD: true
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ghcr.io
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  kc-image:
    name: Build custom keycloak image
    runs-on: ubuntu-latest
    if: github.event.inputs.tag != '' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - id: get_tag
        if: github.event.inputs.tag != '' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop'
        run: |
          if [[ ! -z "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF/refs\/tags\//}
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            TAG="develop"
          else
            TAG="snapshot"
          fi
          echo ::set-output name=tag::${TAG}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push custom Keycloak image
        uses: docker/build-push-action@v3
        with:
          context: keycloak
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/cryptomator/keycloak:${{ steps.get_tag.outputs.tag }}