name: Tag Existing Image

on:
  workflow_dispatch:
    inputs:
      digest:
        description: Digest of Image
        required: true
      tag:
        description: 'Image Tag'
        required: true

defaults:
  run:
    shell: bash

jobs:
  tag:
    name: Tags an existing image
    runs-on: ubuntu-latest
    steps:
      - name: Pull image defined by digest
        run: docker pull ghcr.io/cryptomator/hub@${{ github.event.inputs.digest}}
      - name: Tag image in github registry
        run: docker tag ghcr.io/cryptomator/hub@${{ github.event.inputs.digest}} ghcr.io/cryptomator/hub:${{ github.event.inputs.tag }}
      - name: Push tagged image
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push ghcr.io/cryptomator/hub:${{ github.event.inputs.tag }}